apiVersion: apps/v1
kind: Deployment
metadata:
name: {{ include "demo-app.fullname" . | trunc 63 | trimSuffix "-" }}
labels:
app: {{ include "demo-app.name" . }}
spec:
replicas: {{ .Values.replicaCount }}
selector:
matchLabels:
app: {{ include "demo-app.name" . }}
template:
metadata:
labels:
app: {{ include "demo-app.name" . }}
spec:
containers:
- name: {{ include "demo-app.name" . }}
image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
imagePullPolicy: {{ .Values.image.pullPolicy }}
ports:
- containerPort: {{ .Values.containerPort }}
readinessProbe:
httpGet:
path: /
port: {{ .Values.containerPort }}
initialDelaySeconds: 5
periodSeconds: 5