apiVersion: v1
kind: Service
metadata:
name: {{ include "demo-app.fullname" . | trunc 63 | trimSuffix "-" }}
spec:
type: {{ .Values.service.type }}
selector:
app: {{ include "demo-app.name" . }}
ports:
- port: {{ .Values.service.port }}
targetPort: {{ .Values.containerPort }}
protocol: TCP